/**
 * @module svgmodule
 * @author Vyacheslav Aristov <vv.aristov@gmail.com>
 * @license MIT
 * @see https://www.w3.org/TR/svg
 */
export * from './A'
export * from './Animate'
export * from './Circle'
export * from './ClipPath'
export * from './Defs'
export * from './Desc'
export * from './Ellipse'
export * from './ForeignObject'
export * from './G'
export * from './Line'
export * from './LinearGradient'
export * from './Marker'
export * from './Metadata'
export * from './Path'
export * from './Pattern'
export * from './Polygon'
export * from './Polyline'
export * from './RadialGradient'
export * from './Rect'
export * from './SVGElementAssembler'
export * from './SVGGeometryElementAssembler'
export * from './SVGGradientElementAssembler'
export * from './SVGGraphicsElementAssembler'
export * from './SVGImage'
export * from './SVGSymbol'
export * from './SVGText'
export * from './SVGTextContentElementAssembler'
export * from './SVGTextPositioningElementAssembler'
export * from './Script'
export * from './Stop'
export * from './Style'
export * from './Svg'
export * from './TSpan'
export * from './TextPath'
export * from './Title'
export * from './Use'
export * from './View'
